
name: Node.js CI

on: 
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm i
        cd frontend
        npm i
        npm run build
    
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY_GM}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME_GM}} #Must be unique in Heroku
        heroku_email: ${{secrets.HEROKU_EMAIL_GM}}
